# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:  pretty
markdown:   kramdown
kramdown:
  input: GFM

# Setup
title:               Eventbeyond
tagline:             External API Docs
description:         This is where you can find all the information you need for integrating your data with our system.
url:                 https://danjohnson3141.github.io/pfh_blog
baseurl:             https://danjohnson3141.github.io/pfh_blog
checkmark:           "&#9989;"

# Custom vars
version:             1.0.0
